services:
  recipes:
    container_name: recipes
    build: ./recipes
    volumes:
      - ./recipes/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
    restart: always

  articles:
    container_name: articles
    build: ./articles
    volumes:
      - ./articles/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
    restart: always

  goals:
    container_name: goals
    build: ./goals
    volumes:
      - ./goals/code:/usr/src/app
    networks:
      - mygoals
    ports:
      - "${GOALS_PORT}:${GOALS_PORT}"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
    environment:
      - GOALS_DB_HOST=mysql-server-goals
      - GOALS_DB_NAME=${GOALS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-server-goals
    restart: always

  users:
    container_name: users
    build: ./users
    volumes:
      - ./users/code:/usr/src/app
    networks:
      - myusers
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
    environment:
      - USERS_DB_HOST=mysql-server-users
      - USERS_DB_NAME=${USERS_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-server-users
    restart: always

  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
      - mygoals
      - myusers
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
    environment:
      - PORT=3010
    depends_on:
      - goals
      - users

  mysql-server-goals:
    container_name: mysql-server-goals
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${GOALS_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Only root password, no MYSQL_USER
    ports:
      - "3308:3306"  # Map container's 3306 to host's 3309
    volumes:
      - ./goals/mysql/initdb:/docker-entrypoint-initdb.d
      - mysql-data-goals:/var/lib/mysql
    networks:
      - mygoals  # Ensure mysql-server-articles is on the same network as articles

  mysql-server-users:
    container_name: mysql-server-users
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${USERS_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # Only root password, no MYSQL_USER
    ports:
      - "3309:3306"  # Map container's 3306 to host's 3309
    volumes:
      - ./users/mysql/initdb:/docker-entrypoint-initdb.d
      - mysql-data-users:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - mygoals
      - myusers
    environment:
      - PMA_HOSTS=mysql-server-goals
      - PMA_HOSTS=mysql-server-users
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"

networks:
  msexample:
    driver: bridge
  mygoals:
    driver: bridge
  myusers:
    driver: bridge

volumes:
  mysql-data-goals:
  mysql-data-users: