services:
  articles:
    container_name: articles
    build: ./articles
    volumes:
      - ./articles/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  goals:
    container_name: goals
    build: ./goals
    volumes:
      - ./goals/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  recipes:
    container_name: recipes
    build: ./recipes
    volumes:
      - ./recipes/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm audit && npm install --no-audit && npm run dev"

networks:
  msexample:
    driver: bridge