services:
  articles:
    container_name: articles
    build: ./articles
    volumes:
      - ./articles/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  recipes:
    container_name: recipes
    build: ./recipes
    volumes:
      - ./recipes/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  rabbit_items:
    container_name: rabbit_items
    build: ./rabbit_items
    volumes:
      - ./rabbit_items/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3013:3013"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"   
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge